---
title: "Waze / Economic Shock Test"
author: "Dan Flynn"
date: "12/3/2018"
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---


<!-- saved from url=(0014)about:internet -->
<!-- This needs to be manually added to the second line of the html -->


```{r setup, echo = F, message = F, warning=F}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(tidyverse)
library(DT)
library(lubridate)
library(sp)
library(maps) # for mapping base layers
library(rgdal) # for readOGR(), needed for reading in ArcM shapefiles
library(rgeos) # for gIntersection, to clip two shapefiles

user <- paste0( "/home/", system("whoami", intern = TRUE))
localdir <- paste0(user, "/workingdata/census") # full path for readOGR
teambucket <- "prod-sdc-sdi-911061262852-us-east-1-bucket"
output.loc <- "~/tempout"
codeloc <- "~/SDI_Waze"

```

## Overview

- Test data for economic recovery from natural disasters example
- Find counties impacted by Hurricane Florence, do county level total reports of different types by day,
- Compare to previous year


```{r county_overlay}
state = "NC"

# Done in ReduceWaze_SDC.R
# in two parts: 2018-06  to 2018-10, then 2017-06 to 2017-10
load(file.path(output.loc, "NC_Raw_events_to_2018-10.RData"))
r2018 <- results

load(file.path(output.loc, "NC_Raw_events_to_2017-10.RData"))
r2017 <- results; rm(results)

# Select columns to keep
keep = c("alert_uuid", "uuid_version", "total_occurrences", "alert_type", "sub_type",
         "city", "state", "pub_utc_timestamp","road_type")



# Get spatial data
counties <- rgdal::readOGR(localdir, layer = "cb_2017_us_county_500k")


# Project to Albers equal area, ESRI 102008
proj <- showP4(showWKT("+init=epsg:102008"))
# USGS version of AEA. Use this for all projections for consistency; this is what the hexagon layer is in 
proj.USGS <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0"

counties <- spTransform(counties, CRS(proj.USGS))

FIPS = maps::state.fips %>% filter(abb %in% states)
FIPS = FIPS[!duplicated(FIPS$fips),c("abb", "fips")]
names(FIPS) = c("state", "FIPS")
FIPS$FIPS <- formatC(FIPS$FIPS, width = 2, flag = "0")

  # hex_i_intersect <- gIntersects(xx, hex, byid = T)
  # hex_i <- hex[hex_i_intersect[,1],]
  # #plot(hex_i)

```

