---
title: ''
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

codeloc <- "~/SDI_Waze" 
teambucket <- "s3://prod-sdc-sdi-911061262852-us-east-1-bucket"
user <- paste0( "/home/", system("whoami", intern = TRUE)) # the user directory to use
localdir <- paste0(user, "/workingdata") # full path for readOGR
outputdir <- file.path(localdir, 'Random_Forest_Output')

library(tidyverse)
library(knitr)
library(kableExtra)
library(randomForest)
library(pander)
library(DT)
# Run this if you don't have these packages:
# source(file.path(codeloc, 'utility/get_packages.R'))

knitr::opts_knit$set(root.dir = localdir)

# read utility functions
source(file.path(codeloc, 'utility/wazefunctions.R'))

# read random forest functions
source(file.path(codeloc, "analysis/RandomForest_WazeGrid_Fx.R"))
```

```{r getfiles, message=FALSE, warning=FALSE}

# Pull down model outputs from S3 if necessary
md.files <-  c(
  'MD_VMT_Output_to_30.RData',
  'MD_Model_30_RandomForest_Output.RData',
  'MD_Model_63_RandomForest_Output.RData',
  'MD_Model_62_RandomForest_Output.RData',
  'MD_Model_61_RandomForest_Output.RData')

# MD files
#  system(paste("aws s3 ls", file.path(teambucket, 'MD/')))

for(i in md.files){
  if(length(grep(i, dir(outputdir))) == 0){
    system(paste("aws s3 cp",
                 file.path(teambucket, "MD", i),
                 file.path(outputdir, i)))
  }
}

ct.files <-  c(
  'CT_VMT_Output_to_30.RData',
  'CT_Model_30_RandomForest_Output.RData',
  'CT_Model_63_RandomForest_Output.RData',
  'CT_Model_62_RandomForest_Output.RData',
  'CT_Model_61_RandomForest_Output.RData')

# CT files
#  system(paste("aws s3 ls", file.path(teambucket, 'CT/')))

for(i in ct.files){
  if(length(grep(i, dir(outputdir))) == 0){
    system(paste("aws s3 cp",
                 file.path(teambucket, "CT", i),
                 file.path(outputdir, i)))
  }
}

```

# VMT versus AADT


- Average annual daily traffic (AADT), by sum of the AADT in the roads in a grid cell, from HPMS.

- VMT: Volume of traffic distributed by hour of day, day of week, and month of year from ATR data. Approximately 5,000 stations on the National Highway System (NHS). Hour of year VMT is the product of hour of year volume and HPMS segment length.


```{r CT_MD_VMT_metrics, echo = F}
# Get outputs

load(file.path(outputdir, "MD_VMT_Output_to_30.RData"))

tabl <- vector()
for(i in c("61", "62", "63")){ tabl <- rbind(tabl, c(100*keyoutputs[[i]]$diag, round(keyoutputs[[i]]$auc, 4)))}

colnames(tabl)[1:5] = c("Accuracy", "Precision", "Recall", "False Positive Rate", "AUC")
rownames(tabl) =  c("61 - AADT", "62 - VMT", "63 - AADT + VMT")
datatable(tabl, 
          caption = "VMT model comparisons",
          rownames = T,
          options = list(dom = "t",
                         order = list(list(5, 'desc')),
                         pageLength = 5)
          ) %>% formatCurrency(1:6, currency = "", digits = 2) %>%
          formatStyle(1, background = styleEqual(max(tabl[,1]), 'lightgreen'))%>%
          formatStyle(2, background = styleEqual(max(tabl[,2]), 'lightgreen'))%>%
          formatStyle(3, background = styleEqual(max(tabl[,3]), 'lightgreen'))%>%
          formatStyle(4, background = styleEqual(min(tabl[,4]), 'lightgreen'))%>%
          formatStyle(5, background = styleEqual(max(tabl[,5]), 'lightgreen'))
```   

